# Runs Nginx1, Flask1, Nomad1, Consul1

version: "1.0"

services:
    
  nginx1:
    build: ../../Webserver
    container_name: nginx
    restart: always
    ports:
      - "80:80"

  flask1:
    build: ../../Flask
    container_name: flask
    restart: always
    environment:
      - APP_NAME=MyFlaskApp
    expose:
      - 8080