# Runs Nginx1, Flask1, Nomad1, Consul1

version: "1.0"

services:
    
  nginx1:
    image: ribanerjee.azurecr.io/nginx:1.0
    container_name: nginx
    restart: always
    ports:
      - "80:80"

  flask1:
    image: ribanerjee.azurecr.io/flask:latest
    container_name: flask
    restart: always
    environment:
      - APP_NAME=MyFlaskApp
    expose:
      - 8080